name: Build TWRP Moon

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: debian:11

    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dpkg --add-architecture i386
          apt update

          apt install -y \
          git curl wget unzip zip \
          python3 python-is-python3 \
          build-essential \
          gcc-multilib g++-multilib \
          libc6-dev-i386 \
          lib32ncurses6-dev \
          lib32z1-dev \
          zlib1g-dev \
          flex bison \
          libxml2-utils \
          xsltproc \
          ccache \
          rsync \
          bc

      - name: Install repo
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
          chmod +x /usr/local/bin/repo

      - name: Init TWRP source
        run: |
          mkdir /twrp
          cd /twrp

          repo init \
            -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp \
            -b twrp-12.1

          repo sync -j$(nproc) --force-sync --no-clone-bundle

      - name: Clone device tree
        run: |
          mkdir -p /twrp/device/xiaomi

          git clone \
          https://github.com/4cko/android_device_xiaomi_moon.git \
          /twrp/device/xiaomi/moon

      - name: Build
        run: |
          cd /twrp

          source build/envsetup.sh
          lunch twrp_moon-eng

          mka recoveryimage | tee build.log

      - name: Upload recovery
        uses: actions/upload-artifact@v4
        with:
          name: twrp-moon
          path: |
            /twrp/out/target/product/moon/*.img

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs
          path: |
            /twrp/build.log
